//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace justFeast.cookConvert {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CookingUnitSoap", Namespace="http://www.webserviceX.NET/")]
    public partial class CookingUnit : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ChangeCookingUnitOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CookingUnit() {
            this.Url = global::justFeast.Properties.Settings.Default.justFeast_cookConvert_CookingUnit;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ChangeCookingUnitCompletedEventHandler ChangeCookingUnitCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.webserviceX.NET/ChangeCookingUnit", RequestNamespace="http://www.webserviceX.NET/", ResponseNamespace="http://www.webserviceX.NET/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double ChangeCookingUnit(double CookingValue, Cookings fromCookingUnit, Cookings toCookingUnit) {
            object[] results = this.Invoke("ChangeCookingUnit", new object[] {
                        CookingValue,
                        fromCookingUnit,
                        toCookingUnit});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void ChangeCookingUnitAsync(double CookingValue, Cookings fromCookingUnit, Cookings toCookingUnit) {
            this.ChangeCookingUnitAsync(CookingValue, fromCookingUnit, toCookingUnit, null);
        }
        
        /// <remarks/>
        public void ChangeCookingUnitAsync(double CookingValue, Cookings fromCookingUnit, Cookings toCookingUnit, object userState) {
            if ((this.ChangeCookingUnitOperationCompleted == null)) {
                this.ChangeCookingUnitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChangeCookingUnitOperationCompleted);
            }
            this.InvokeAsync("ChangeCookingUnit", new object[] {
                        CookingValue,
                        fromCookingUnit,
                        toCookingUnit}, this.ChangeCookingUnitOperationCompleted, userState);
        }
        
        private void OnChangeCookingUnitOperationCompleted(object arg) {
            if ((this.ChangeCookingUnitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChangeCookingUnitCompleted(this, new ChangeCookingUnitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.webserviceX.NET/")]
    public enum Cookings {
        
        /// <remarks/>
        drop,
        
        /// <remarks/>
        dash,
        
        /// <remarks/>
        pinch,
        
        /// <remarks/>
        milliliterPerCC,
        
        /// <remarks/>
        deciliter,
        
        /// <remarks/>
        coffeeSpoon,
        
        /// <remarks/>
        fluidDram,
        
        /// <remarks/>
        teaspoonUS,
        
        /// <remarks/>
        teaspoonUK,
        
        /// <remarks/>
        tablespoonUS,
        
        /// <remarks/>
        tablespoonUK,
        
        /// <remarks/>
        fluidOunceUS,
        
        /// <remarks/>
        fluidOunceUK,
        
        /// <remarks/>
        cupUS,
        
        /// <remarks/>
        cubicInch,
        
        /// <remarks/>
        gillUS,
        
        /// <remarks/>
        gillUK,
        
        /// <remarks/>
        pintUS,
        
        /// <remarks/>
        pintUK,
        
        /// <remarks/>
        quartUS,
        
        /// <remarks/>
        liter,
        
        /// <remarks/>
        gallonUS,
        
        /// <remarks/>
        gallonUK,
        
        /// <remarks/>
        TwoPointFiveCan,
        
        /// <remarks/>
        TenCan,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ChangeCookingUnitCompletedEventHandler(object sender, ChangeCookingUnitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChangeCookingUnitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChangeCookingUnitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591